#!/bin/bash
#PBS -P dt6
#PBS -q hugemem
#PBS -l ncpus=4
#PBS -l mem=400GB
#PBS -l walltime=32:00:00
#PBS -l storage=gdata/xp65+gdata/zz63+gdata/dt6+scratch/w97+gdata/w97+gdata/zv2
#PBS -N sm_agg
#PBS -j oe

# Load the Singularity‑wrapped analysis3 environment
module use /g/data/xp65/public/modules
module load conda/analysis3

# Move to the directory where the job was submitted
cd /home/561/mg5624/future_yield/extremes/

# Run your script
python extremes_characteristics_nc.py