#!/bin/bash
#PBS -P dt6
#PBS -q normal
#PBS -l ncpus=1
#PBS -l mem=80GB
#PBS -l walltime=12:00:00
#PBS -l storage=gdata/xp65+gdata/zz63+gdata/dt6+scratch/w97+gdata/w97+gdata/zv2
#PBS -N fill_na_intensity
#PBS -j oe

# Load the Singularity‑wrapped analysis3 environment
module use /g/data/xp65/public/modules
module load conda/analysis3

# Move to the directory where the job was submitted
cd /home/561/mg5624/yield_trends/extremes/

# Run your script
python fill_na_intensity.py
