#!/bin/bash
#PBS -P dt6
#PBS -q normal
#PBS -l ncpus=4
#PBS -l mem=50GB
#PBS -l walltime=2:00:00
#PBS -l storage=gdata/xp65+gdata/zz63+gdata/dt6+scratch/w97+gdata/w97
#PBS -N pdp_summary
#PBS -j oe

# Load the Singularity‑wrapped analysis3 environment
module use /g/data/xp65/public/modules
module load conda/analysis3

# Move to the directory where the job was submitted
cd /home/561/mg5624/future_yield/extremes/

# Run your script
python pdp_summary.py